### PR TITLE
Correct aliasing of new/open for CAF::FileWriter/Editor/Reader

### LINKED ISSUE #139: CAF::FileReader example use does not work
CAF::FileReader includes the following sample code but [a search ](https://github.com/quattor/configuration-modules-core/search?utf8=%E2%9C%93&q=FileReader&type=Code) of the code base shows no actual examples of its use.

```
    use CAF::FileReader;
    my $fh = CAF::FileReader->open ("my/path");
    while (my $line = <$fh>) {
       # Do something
    }
```

In testing, this doesn't work. ```print "$fh"``` does work because of stringify().  This works:

```
my $fh = CAF::FileReader->open("/path/to/file");
foreach my $line (split(/\n/, "$fh")) {
    print "$line\n";
}
```

Unclear if this is a documentation bug or if filehandle syntax should work?

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #139

### CODE REVIEW

**Comment by stdweird** [comment]
The unittest failed for original Writer and Reader, so expect some strange stuff.
Also 'requires perl guru' to know why the old code was wrong.
@jrha i'll leave the milestone up to you

**Comment by ned21** [comment]
Assuming we want to continue to have open as a synonym for new this looks fine. I'd suggest 16.4 in case this introduces some subtle bugs that delay the release.

**Comment by jrha** [comment]
@stdweird Github is telling me this needs to be rebased

**Comment by stdweird** [comment]
and now it has

**Comment by jrha** [comment]
Excellent

**Pull request merged**
