### PR TITLE
CAF::Download::LWP: CAF interface for LWP to handle https settings

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
is the code from https://github.com/quattor/configuration-modules-core/pull/925

**Comment by stdweird** [comment]
also more testing

**Comment by ned21** [comment]
It took me a while to understand the pom.xml changes in 985234d. Looks like they are necessary because this introduces a new subdir - can that be called out in the commit log please?

**Comment by stdweird** [comment]
@ned21 pom.xml chnages made in separate commit

**Comment by stdweird** [comment]
@ned21 @jrha pls merge, there are a few other PRs that depend on this one

**Pull request merged**
