### PR TITLE
Kerberos support via GSSAPI

### PR DESCRIPTION
**Pull request by stdweird**
Based on #120 

Important to note that kinit is not required at all.

### CODE REVIEW

**Comment by stdweird** [comment]
GSSAPI is easy once you know how it works, but until then, you are stuck reading krb5-devel and the GSSAPI XS code, and lots of try and error :smile:

**Comment by ned21** [comment]
Nothing obviously wrong jumps out at me but I'm not familiar at all with GSSAPI :(

**Comment by jrha** [comment]
@stdweird rebase?

**Comment by stdweird** [comment]
@jrha rebased

**Pull request merged**
