### PR TITLE
FileWriter/Editor: add reopen method

### PR DESCRIPTION
**Pull request by stdweird**
Requires #238

### CODE REVIEW

**Comment by jrha** [comment]
LGTM, but I'm no perl/CAF guru.

**Comment by ned21** [comment]
Looks like only 37db65a is new and the rest already merged so this needs a rebase.

Regarding 37db65a, I am not sure I understand why this is useful and where it is intended to be used. I'm unsure as to whether that is best made part of the POD for the method, or in the commit log.

**Comment by stdweird** [comment]
@ned21 i wrote this code because i was trying to do something clever in the network rewrite with initial write and close from source, and then another write (in summary: i was too lazy of call copy 😄 ).

i now also see 2 minor changes that could be useful otherwise: handle close an already closed file and handle the stringification of a closed file.

**Comment by ned21** [comment]
tbh I'm not convinced this is useful. It's an extra function which has to be maintained and tested against all future changes -- additional rarely used code is a maintenance burden -- and does it really save any code for the user?

**Comment by stdweird** [comment]
@ned21 ok. i'll try to extract the 2 minor changes/fixes that are useful in another PR. we can always reopen this PR is guess

**Pull request closed without merging**
