### PR TITLE
remove set_caf_file_close_diff and unneeded NoAction from rbe unittests

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
retest this please

**Comment by ned21** [comment]
Could the commit log explain why are they unneeded/safe to remove please?

**Comment by stdweird** [comment]
@ned21 not how to formulate that
* `set_caf_file_close_diff` is a noop in 1.54 and scheduled for removal in 1.55 (https://github.com/quattor/maven-tools/pull/162)
* the rbe unittests do not test NoAction, so it is not needed to specify that anymore (NoAction was used in unittests to prevent actual files being written etc; but since 1.54, this is no longer needed as everything is mocked when using `Test::Quattor` in unittests; and setting NoAction should only be done to test NoAction behaviour)

**Comment by ned21** [comment]
@stdweird What you have written in the comment is perfect - it just needs to be in the commit log so we can preserve it if GH disappears / we migrate to something else.

**Comment by stdweird** [comment]
@ned21 commit message modified

**Comment by jrha** [comment]
@hpcugentbot test this please

**Pull request merged**
