### PR TITLE
Path: move: do not cleanup dest, but add backup of dest using hardlink

### PR DESCRIPTION
**Pull request by stdweird**
Fixes https://github.com/quattor/configuration-modules-core/issues/991

### CODE REVIEW

**Comment by ned21** [comment]
LGTM. Any chance of splitting the whitespace and comment cleanups earlier in the file into a separate commit?

**Comment by stdweird** [comment]
aaaarghhhhh. that's my save.
agree to enforce http://search.cpan.org/~thaljef/Perl-Critic/lib/Perl/Critic/Policy/CodeLayout/ProhibitTrailingWhitespace.pm?

**Comment by ned21** [comment]
@stdweird I'm fine with the policy in principle (it's same as pep8, right?) but a little bit nervous about the amount of clean up required?

**Comment by stdweird** [comment]
@ned21 should be trivial in any editor; and most components are not on `00-tqu` yet.

**Comment by stdweird** [comment]
@ned21 whitespace changes in separate commit

**Pull request merged**
