### PR TITLE
FileWriter: add conditional logger interfaces

### PR DESCRIPTION
**Pull request by stdweird**
Requires new build-scripts with https://github.com/quattor/maven-tools/pull/80

### CODE REVIEW

**Comment by stdweird** [comment]
based on #155 which has the buildtools versionbump
tests pass again

**Comment by jrha** [comment]
test this please

**Comment by stdweird** [comment]
@jouvin incl the RuleBasedEditor

**Comment by jrha** [comment]
LGTM (as far as I can tell)

**Comment by ned21** [comment]
This just does ```*$self->{LOG}->debug(...)``` -> `$self-debug(...)```. That's nicer to look at but a longer explanation of why and how would be good!

**Comment by jouvin** [comment]
As said (suggested!) in the initial description,  https://github.com/quattor/CAF/pull/154#issuecomment-218285819 defined the usual `error()`, `debug()` method in the test context where they were undefined for things other than a component (no reporter). This allows both a more readable code and also a simpler one as `$self->{LOG}` can be undefined and thus every `$self->{LOG}->xxx(...)` had to be followed by `if $self->{LOG}`.

**Comment by stdweird** [comment]
@ned21 the conditional reporter interface is already part of `CAF::Object`, and as @jouvin pointed out, the main benefit is that you can get rid of the `if *$self->{LOG}` in the code.

**Pull request merged**
