### PR TITLE
TextRender: general/Config::General disable SaveSorted and enable ForceArray

### LINKED ISSUE #81: TextRender Config::General ordering issues on EL6
Below some debug data from `TextRender` with `general` module (a.k.a `Config::General`).
The `service` entry is a list, but the generation of the text does not keep that order on EL6.

```
# _store ARRAY HASH entry site line HASH(0x1221110)<site>
# _store $VAR1 = {
#           'site_location' => 'HERE',
#           'site_project' => [
#                             'MYSITE'
#                           ],
#           'address' => 'my.host.domain',
#           'site_name' => 'MYSITE',
#           'service' => [
#                        {
#                          'type' => 'bwctl'
#                        },
#                        {
#                          'type' => 'owamp'
#                        }
#                      ],
#           'is_local' => 1
#         };
# _store SCALAR entry address    address   my.host.domain
# _store SCALAR entry is_local    is_local   1
# _store ARRAY HASH entry service line HASH(0x1220df8)    <service>
# _store $VAR1 = {
#           'type' => 'owamp'
#         };
# _store SCALAR entry type        type   owamp
#     </service>
# _store ARRAY HASH entry service line HASH(0x1220e40)    <service>
# _store $VAR1 = {
#           'type' => 'bwctl'
#         };
# _store SCALAR entry type        type   bwctl
#     </service>
# _store SCALAR entry site_location    site_location   HERE
# _store SCALAR entry site_name    site_name   MYSITE
# _store ARRAY SCALAR entry site_project line MYSITE    site_project   MYSITE
# </site>
```

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #81

`general` / Config::General has reproducability issues, should be avoided if possible

### CODE REVIEW

**Comment by stdweird** [comment]
This is based on #77

**Comment by stdweird** [comment]
test fails because ... `Config::General` is not reproducabile: works fine on laptop (perl 5.18), not so on jenkins box (perl 5.14).

**Comment by jrha** [comment]
LGTM

**Comment by stdweird** [comment]
retest this please

**Pull request merged**
